### ISSUE TITLE
Cannot create a Power Managed Zone

### ISSUE THREAD

**Issue by zijam** [callionica/hue#1]
When I click on `Create` button in `Power Managed Zone` page, nothing happens.
I can see in the console log, there is an uncaught error.
```
hue-callionica-power-managed-zone.html:79 Uncaught TypeError: Cannot read properties of undefined (reading 'text')
    at hue-callionica-power-managed-zone.html:79
    at Array.map (<anonymous>)
    at hue-callionica-power-managed-zone.html:79
    at Array.map (<anonymous>)
    at settings (hue-callionica-power-managed-zone.html:78)
    at HTMLButtonElement.onCreate (hue-callionica-power-managed-zone.html:122)
```

Any idea on what is wrong? 

![Screenshot 2021-12-23 at 20 31 00](https://user-images.githubusercontent.com/695088/147284495-2c63c9c7-58eb-4ae9-bbf8-f54acc994442.png)

**Comment by callionica** [comment]
Do you have connection(s) set up to your bridge?

Also need to select scenes for each of the full power and low power entries.
